### ISSUE TITLE
MinRAMPercentage and MaxRAMPercentage is ignored on Transform Core AIO

### ISSUE THREAD

**Issue by iohann95** [Alfresco/alfresco-docker-installer#135]
Hello,

Sometimes when uploading a large number of files using WebDAV, my transform-core-aio container crashes with 137 OOM error.

![image](https://user-images.githubusercontent.com/63069860/169819762-a6be0582-4c8a-4fef-a4d1-3deacfd25319.png)

I'm using 16GB of RAM on the installer, using default memory parameters.

It does seems to be resolved if I configure -Xms and -Xmx. I think MinRAMPercentage and MaxRAMPercentage isn't working.

Let me know if you need any more info.

Regards,
Iohann

**Comment by aborroy** [comment]
"transform-core-aio" container is created with a fixed amount of RAM (1536m):

https://github.com/Alfresco/alfresco-docker-installer/blob/master/generators/app/templates/7.2/docker-compose.yml#L122

If, like in your use case, it's required additional memory, the recommended approach is to increase that default value. For instance, to use 2 GB:

```
    transform-core-aio:
        image: alfresco/alfresco-transform-core-aio:${TRANSFORM_ENGINE_TAG}
        mem_limit: 2048m
```

No sure if some option can be added to the `alfresco-docker-installer` tool in order to set this value.

**Comment by iohann95** [comment]
I understand, you're right that it's best to increase the container memory. But I tough that MaxRAMPercentage would prevent it from crashing. That wasn't the expected end result?

**Comment by aborroy** [comment]
`-XX:MaxRAMPercentage=80` with default setting (1536 MB) should allow to use 1536x0.80=1228 MB

The amount of memory for the container is limited by that `mem_limit` value.
